# Generated by Django 5.2.3 on 2025-07-03 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_userprofile_options_destination_is_popular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured hotel'),
        ),
    ]
