# Generated by Django 5.2.3 on 2025-07-03 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_hotel_created_at_hotel_description_hotel_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transport',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='transports/'),
        ),
        migrations.AddField(
            model_name='transport',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Mark as popular transport'),
        ),
    ]
