# Generated by Django 5.2.3 on 2025-07-09 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_transport_created_at_transport_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destinations/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('is_cover', models.BooleanField(default=False, help_text='Use as cover image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.destination')),
            ],
            options={
                'verbose_name': 'Destination Image',
                'verbose_name_plural': 'Destination Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('is_cover', models.BooleanField(default=False, help_text='Use as cover image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Image',
                'verbose_name_plural': 'Hotel Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('is_cover', models.BooleanField(default=False, help_text='Use as cover image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.package')),
            ],
            options={
                'verbose_name': 'Package Image',
                'verbose_name_plural': 'Package Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transports/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('is_cover', models.BooleanField(default=False, help_text='Use as cover image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.transport')),
            ],
            options={
                'verbose_name': 'Transport Image',
                'verbose_name_plural': 'Transport Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
