# Generated by Django 5.2.3 on 2025-07-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_destinationimage_hotelimage_packageimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords/tags for searching, separated by commas (e.g., beach, mountain, adventure, cultural)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords/tags for searching, separated by commas (e.g., luxury, budget, spa, pool, wifi)'),
        ),
        migrations.AddField(
            model_name='package',
            name='hotels',
            field=models.ManyToManyField(blank=True, help_text='Hotels included in this package', to='travel.hotel'),
        ),
        migrations.AddField(
            model_name='package',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords/tags for searching, separated by commas (e.g., adventure, luxury, budget, family)'),
        ),
        migrations.AddField(
            model_name='package',
            name='transports',
            field=models.ManyToManyField(blank=True, help_text='Transports included in this package', to='travel.transport'),
        ),
        migrations.AddField(
            model_name='transport',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords/tags for searching, separated by commas (e.g., fast, comfortable, budget, luxury)'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_type',
            field=models.CharField(choices=[('flight', 'Flight'), ('bus', 'Bus'), ('train', 'Train'), ('car', 'Car Rental'), ('boat', 'Boat'), ('taxi', 'Taxi')], max_length=20),
        ),
    ]
