# Generated by Django 5.2.3 on 2025-07-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_destination_keywords_hotel_keywords_package_hotels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='hotels',
            field=models.ManyToManyField(blank=True, help_text='Hotels included in this package', related_name='packages', to='travel.hotel'),
        ),
        migrations.AlterField(
            model_name='package',
            name='transports',
            field=models.ManyToManyField(blank=True, help_text='Transports included in this package', related_name='packages', to='travel.transport'),
        ),
    ]
