# Generated by Django 5.2.3 on 2025-07-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_package_hotels_alter_package_transports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='hotels',
            field=models.ManyToManyField(help_text='Hotels included in this package (At least one hotel must be selected)', related_name='packages', to='travel.hotel'),
        ),
    ]
