# Generated by Django 5.2.3 on 2025-07-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_package_hotels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='destination',
        ),
        migrations.AddField(
            model_name='package',
            name='destinations',
            field=models.ManyToManyField(help_text='Destinations included in this package', related_name='packages', to='travel.destination'),
        ),
    ]
